Public Class ER_Employee_DB
    Public Property Repository_ID As String
    Public Property Employee_ID As String
    Public Property Employee_Name As String
    Public Property Address As String
    Public Property City As String
    Public Property State As String
    Public Property Zip_Code As String
    Public Property Mobile_Phone As String
    Public Property Home_Phone As String
    Public Property Work_Phone As String
    Public Property Department As String
    Public Property Cost_Center As String
    Public Property Email_Address As String
    Public Property Manager_ID As String
    Public Property Resident_Address As String
    Public Property Employee_Grade As String
    Public Property New_Identity_Card As String
    Public Property Old_Identity_Card As String
    Public Property Branch As String
    Public Property Status As String
    Public Property Position As String
    Public Property Day_Start As String
    Public Property Day_End As String
    Public Property Employee_Type As String
    Public Property Nationality As String
    Public Property Passport_No As String
    Public Property Country_Code As String
    Public Property Country As String
    Public Property Marital_Status As String
    Public Property Emergency_Contact_Name As String
    Public Property Emergency_Contact_Number As String
    Public Property Emergency_Contact_Address As String
    Public Property Photo As String
    Public Property Employee_Race As String
    Public Property Date_of_Birth As String
    Public Property Gender As String
    Public Property backupNo2 As String
    Public Property backupNo1 As String
    Public Property EMPLOYEE_CATEGORY As String
    Public Property Employee_Group_1 As String
    Public Property Birth_Place As String
    Public Property Employee_Name_Chinese As String
    Public Property Resident_Phone As String
    Public Property Spouse_Name As String
    Public Property Spouse_Relationship As String
    Public Property Sponse_Career As String
    Public Property Secondary_Phone_Number As String
    Public Property EMERGENCY_RELATIONSHIP As String
    Public Property EMPLOYEE_TYPE_2 As String
    Public Property Education_Level As String
    Public Property Education_Remark As String
    Public Property Address_No1 As String
    Public Property Address_No2 As String
    Public Property Resident_Address_No1 As String
    Public Property Resident_Address_No2 As String
    Public Property New_Category As String
    Public Property Insurance_No As String
    Public Property Token As String
    Public Property Categoryid As String
    Public Property University_Name As String
    Public Property IG As String
    Public Property SPIKPA As String
    Public Property SPPA As String
    Public Property Insurance_Agent As String
    Public Property Agent As String
    Public Property Smock_Size As String
    Public Property Shoes_Size As String
    Public Property Hostel_Code As String
    Public Property Hostel_Address As String
    Public Property Permit_Number As String
    Public Property Passport_For_Sticker As String
    Public Property Locker_Number As String
    Public Property Insurance_Start_Date As String
    Public Property Insurance_End_Date As String
    Public Property Smock_Issue_Date As String
    Public Property Shoes_Issue_Date As String
    Public Property Manager_ID_Second As String
    Public Property Manager_ID_Third As String
    Public Property LM_CAT As String
    Public Property RELIGION As String
    Public Property EMP_QUERY As String
    Public Property Perfect_Att As String
    Public Property TABUNG_HAJI As String
    Public Property Amanah_Saham As String
    Public Property ZAKAT As String
    Public Property EMPLOYEE_L_TYPE As String

    Public Property Payroll_ID As String
    Public Property Deduction_for_Spouse As String
    Public Property Total_for_Children As String
    Public Property Deduction_for_Individual As String
    Public Property Basic_Salary As String
    Public Property Employee_EPF As String
    Public Property Employer_EPF As String
    Public Property Overtime_Rate As String
    Public Property Tax_Reference_No As String
    Public Property Wife_Code As String
    Public Property Record_Type As String
    Public Property Employer_No As String
    Public Property Category As String
    Public Property Total_Pre_Salary As String
    Public Property Total_Pre_EPF As String
    Public Property Under_18_Age As String
    Public Property Above_18_Full_Time_Certificate As String
    Public Property Above_18_Full_Time_Degree As String
    Public Property Disabled_Child As String
    Public Property Disabled_Child_Study As String
    Public Property EPF_No As String
    Public Property Company_ID As String
    Public Property Bank_ID As String
    Public Property EPF_Category As String
    Public Property SOCSO_Type As String
    Public Property SOCSO_No As String
    Public Property EPF_19Percent As String
    Public Property Advanced_Salary As String
    Public Property Advanced_Salary_Amount As String
    Public Property Account_Classification As String
    Public Property Receiving_Member_Bank As String
    Public Property Rentas_Transaction_Code As String
    Public Property Rentas_Status As String
    Public Property Previous_AR As String
    Public Property Previous_AR_EPF As String
    Public Property Previous_PCB As String
    Public Property Date_Confirmation As String
    Public Property OT_LEVEL As String
    Public Property OT_RESTRICTION As String
    Public Property PAYMENT_METHOD As String
    Public Property PAYMENT_STATUS As String
    Public Property PAYOUT_TYPE As String
    Public Property EMPLOYEE_DAYS As String
    Public Property PREFIX As String
    Public Property TRANSPORT As String
    Public Property EMPLOYEE_STATUS_V3 As String
    Public Property RETIRE_AGE As String
    Public Property PASSPORT_EXPIRE As String
    Public Property DIRECT_SUPERIOR As String
    Public Property WORK_PERMIT As String
    Public Property OTHOUR As String
    Public Property START_DATE As String
    Public Property END_DATE As String
    Public Property Month_Diff As String

End Class

